//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Parent_Guardian = new HashSet<Parent_Guardian>();
        }
    
        public int Application_ID { get; set; }
        public Nullable<int> Application_Status_ID { get; set; }
        public Nullable<System.DateTime> Application_Date { get; set; }
        public string Parent_Name { get; set; }
        public string Parent_Surname { get; set; }
        public string Parent_Contact_No { get; set; }
        public string Parent_Email { get; set; }
        public string Student_Name { get; set; }
        public string Student_Surname { get; set; }
        public Nullable<int> Student_Grade { get; set; }
    
        public virtual Application_Status Application_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parent_Guardian> Parent_Guardian { get; set; }
    }
}
