//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int Class_ID { get; set; }
        public string Class_Name { get; set; }
        public string Class_Capacity { get; set; }
        public Nullable<int> Student_ID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
