//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Line
    {
        public int Supplier_Order_ID { get; set; }
        public int Order_Type_ID { get; set; }
        public int Stationery_ID { get; set; }
        public int Cleaning_Material_Item_ID { get; set; }
        public int Equipment_ID { get; set; }
        public string Order_Line_Item { get; set; }
    }
}
