//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public string Proof_Of_Payment { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Payment_Status { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
