//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Term
    {
        public int School_Term_ID { get; set; }
        public Nullable<int> Schedule_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> Report_Card_ID { get; set; }
        public string Term_details { get; set; }
    
        public virtual ReportCard ReportCard { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Student Student { get; set; }
    }
}
