//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Fees
    {
        public int School_Fees_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<decimal> Fee_Amount { get; set; }
        public Nullable<decimal> Amount_Outstanding { get; set; }
        public Nullable<decimal> Last_Payment { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
