//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public int Title_ID { get; set; }
        public string Mr { get; set; }
        public string Mrs { get; set; }
        public string Ms { get; set; }
        public string Dr { get; set; }
    }
}
