//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Application_ID { get; set; }
        public Nullable<int> Parent_Guardian_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> Application_Status_ID { get; set; }
        public Nullable<System.DateTime> Application_Date { get; set; }
    
        public virtual Application_Status Application_Status { get; set; }
        public virtual Parent_Guardian Parent_Guardian { get; set; }
        public virtual Student Student { get; set; }
    }
}
