//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateTable
    {
        public int Date_ID { get; set; }
        public string Date_details { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
    }
}
