//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emergency
    {
        public int Emergency_ID { get; set; }
        public string Emergency_Details { get; set; }
        public Nullable<System.DateTime> Emergency_Date { get; set; }
    }
}
