//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Type
    {
        public int Employee_Type_ID { get; set; }
        public string Teacher { get; set; }
        public string Cook { get; set; }
        public string Gardener { get; set; }
        public string Administrator { get; set; }
        public string Principal { get; set; }
    }
}
