//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Equipment_ID { get; set; }
        public string Equipment_Item_Name { get; set; }
        public Nullable<System.DateTime> Equipment_Purchase_Date { get; set; }
        public Nullable<int> Equipment_Type_ID { get; set; }
    
        public virtual Equipment_Type Equipment_Type { get; set; }
    }
}
