//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marking_Scale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marking_Scale()
        {
            this.Progress_Category = new HashSet<Progress_Category>();
        }
    
        public int Marking_Scale_ID { get; set; }
        public Nullable<int> Report_Card_Template_ID { get; set; }
        public string Marking_Scale_Details { get; set; }
    
        public virtual ReportCard_Template ReportCard_Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progress_Category> Progress_Category { get; set; }
    }
}
