//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Item
    {
        public int Menu_Item_ID { get; set; }
        public string Menu_Item_Description { get; set; }
        public Nullable<int> Menu_Items_Purchased { get; set; }
        public Nullable<System.DateTime> Menu_Item_Purchase_Date { get; set; }
    }
}
