//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Fees_Status
    {
        public int School_Fees_Status_ID { get; set; }
        public string School_Fees_Status_Description { get; set; }
        public Nullable<int> Parent_Guardian_ID { get; set; }
    
        public virtual Parent_Guardian Parent_Guardian { get; set; }
    }
}
