//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategory
    {
        public int Subcategory_ID { get; set; }
        public Nullable<int> Progress_Category_ID { get; set; }
        public string Subcategory_Details { get; set; }
    
        public virtual Progress_Category Progress_Category { get; set; }
    }
}
