//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrayonKidsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Tbl
    {
        public int User_Tbl_ID { get; set; }
        public Nullable<int> User_Type_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual User_Type User_Type { get; set; }
    }
}
